# Generated by Django 4.2 on 2023-06-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Price', '0002_productinbasket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='nmb',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='nmb',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='total_price',
        ),
    ]
