# Generated by Django 4.2 on 2023-04-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
