# Generated by Django 4.2 on 2023-05-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfol', '0002_alter_portfolio_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
